name: Build and Publish Web Site

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Build and Deploy Website
    runs-on: ubuntu-latest

    steps:
      - name: Check out code using Git
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm i

      # Step 4: Build the project
      - name: Build
        run: pnpm run build

      # Step 5: Redirect 404 to index.html for SPA
      - name: Setup SPA Redirect
        run: cp dist/index.html dist/404.html

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: docs.angor.io
